---
title: "visualizing candidates"
author: "Seren Villwock"
date: "1/28/2021"
output: html_document
---
Read in lists
```{r}
library(ggplot2)

candidates <- read.table("~/Desktop/Research/KASP_design/candidates0128.txt")
candidates$pos.list <- candidates$V1
candidates$pos.range <- candidates$pos.list + 1
candidates <- as.data.frame(candidates)

conserved <- read.table("~/Desktop/Research/KASP_design/conservedsites0128.txt")
conserved$pos.list <- conserved$V1
conserved$pos.range <- conserved$pos.list + 1
conserved <- as.data.frame(conserved)


#data <- list(candidates.start=candidates$pos.list, candidates.stop=candidates$pos.range, conserved.start=conserved$pos.list, conserved.stop=conserved$pos.range)

library(tidyverse)
df4 <- data.frame(stringsAsFactors = FALSE,
                 candidates.start = c(candidates$pos.list))
df3 <- data.frame(stringsAsFactors = FALSE,
                 candidates.stop = c(candidates$pos.range))
df2 <- data.frame(stringsAsFactors = FALSE,
                 conserved.start = c(conserved$pos.list))
df1 <- data.frame(stringsAsFactors = FALSE,
                 conserved.stop = c(conserved$pos.range))

data <- df1 %>%
    rownames_to_column() %>% 
    left_join(df2 %>% rownames_to_column()) %>% 
    left_join(df3 %>% rownames_to_column()) %>% 
    left_join(df4 %>% rownames_to_column()) %>% 
    select(-rowname)

```
```{r}
ggplot(data=data) +
  geom_segment(aes(x=candidates.start, xend=candidates.stop, y=0, yend=1), color="steelblue", size=0.1) +
  #geom_segment(aes(x=conserved.start, xend=conserved.stop, y=0, yend=1), color="red", size=0.001, alpha=0.05) +
  scale_y_continuous(labels=NULL)
```


Visualize
```{r}
aspect_ratio <- 10
height <- 5


ggsave(plot, height = height, width = height  * aspect_ratio)
```

